# Generated by Django 4.2.1 on 2023-06-22 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("item", "0006_remove_item_cart"),
        ("cart", "0005_alter_cart_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="item",
            field=models.ForeignKey(
                blank=True,
                max_length=255,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="item.item",
                verbose_name="Item",
            ),
        ),
    ]
