# Generated by Django 4.2.1 on 2023-06-22 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("item", "0007_remove_item_order"),
        ("order", "0003_remove_order_item"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="item",
            field=models.ForeignKey(
                blank=True,
                max_length=255,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="item.item",
                verbose_name="Item",
            ),
        ),
    ]
