# Generated by Django 3.2.19 on 2023-05-22 19:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0002_auto_20230522_2152"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="is_staff",
            field=models.BooleanField(default=True, verbose_name="Is superuser"),
        ),
    ]
