# Generated by Django 4.2.1 on 2023-06-22 09:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0005_alter_user_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="birth_date",
            field=models.CharField(
                default="10.03.1995", max_length=255, verbose_name="Birth date "
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="city",
            field=models.CharField(
                default="Moscow", max_length=255, verbose_name="City "
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="phone",
            field=models.CharField(
                default="+7 910 313 11 44", max_length=15, verbose_name="Phone "
            ),
        ),
    ]
