# Generated by Django 4.2.1 on 2023-06-22 10:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0007_alter_user_is_staff"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(
                default="+7 910 313 11 44", max_length=20, verbose_name="Phone "
            ),
        ),
    ]
