# Generated by Django 4.2.1 on 2023-06-21 19:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_logging", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="request",
            name="response_date",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 6, 21, 22, 5, 52, 341407)
            ),
        ),
    ]
