# Generated by Django 4.2.1 on 2023-06-22 10:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("item", "0004_alter_item_cart_alter_item_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="type",
            field=models.CharField(
                choices=[
                    ("GUITAR", "Guitar"),
                    ("AMP", "Amp"),
                    ("ACCESSUAR", "Accessuar"),
                ],
                default="GUITAR",
                max_length=255,
                verbose_name="Item type",
            ),
        ),
    ]
