# Generated by Django 4.2.1 on 2023-06-22 13:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("item", "0007_remove_item_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="image",
            field=models.ImageField(
                null=True, upload_to="images", verbose_name="Item image "
            ),
        ),
    ]
